/**
 * Created by saionara1 on 6/22/17.
 */

export const LOGIN_ACTION = "LOGIN";
export const LOGOUT_ACTION = "LOGOUT";
export const LOGIN_SUCCESS = "LOGIN_SUCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_ERROR = "LOGOUT_ERROR";
export const PROGRESS = "PROGRESS";

// get contact
export const GET_CONTACT = "GET_CONTACT";
export const GET_CONTACT_SUCCESS = "GET_CONTACT_SUCCESS";
export const GET_CONTACT_ERROR = "GET_CONTACT_ERROR";


// get calender
export const RESET_CALENDAR_DATA = "RESET_CALENDAR_DATA";
export const GET_CALENDAR = "GET_CALENDAR";
export const GET_CALENDAR_SUCCESS = "GET_CALENDAR_SUCCESS";
export const GET_CALENDAR_ERROR = "GET_CALENDAR_ERROR";


// get báo cáo văn bản
export const GET_REPORT_DOCUMENT = "GET_REPORT_DOCUMENT";
export const GET_REPORT_DOCUMENT_SUCCESS = "GET_REPORT_DOCUMENT_SUCCESS";
export const GET_REPORT_DOCUMENT_ERROR = "GET_REPORT_DOCUMENT_ERROR";

// get báo cáo công việc
export const GET_REPORT_WORD = "GET_REPORT_WORD";
export const GET_REPORT_WORD_SUCCESS = "GET_REPORT_WORD_SUCCESS";
export const GET_REPORT_WORD_ERROR = "GET_REPORT_WORD_ERROR";

export const ACTION_REPOSITORIES_LIST = "ACTION_REPOSITORIES_LIST";
export const ACTION_LIST_ERROR = "ACTION_LIST_ERROR";
export const ACTION_LIST_SUCCESS = "ACTION_LIST_SUCCESS";


export const ACTION_README = "ACTION_README";
export const ACTION_README_SUCCESS = "ACTION_README_SUCCESS";
export const ACTION_README_ERROR = "ACTION_README_ERROR";

// get quản lý văn bản
export const GET_LIST_DOCUMENT = "GET_LIST_DOCUMENT";
export const GET_ITEM_DOCUMENT_EVENT = "GET_ITEM_DOCUMENT_EVENT";
export const GET_LIST_WAITING_DOCUMENT = "GET_LIST_WAITING_DOCUMENT";
export const GET_LIST_PROCESSED_DOCUMENT = "GET_LIST_PROCESSED_DOCUMENT";
export const GET_LIST_WAITING_DOCUMENT_SUCESS = "GET_LIST_WAITING_DOCUMENT_SUCESS";
export const RESET_LIST_DOCUMENT = "RESET_LIST_DOCUMENT";
export const GET_LIST_PROCESSED_DOCUMENT_SUCESS = "GET_LIST_PROCESSED_DOCUMENT_SUCESS";
export const GET_LIST_DOCUMENT_ERROR = "GET_LIST_DOCUMENT_ERROR";
export const GET_LIST_DOCUMENT_SUCCESS = "GET_LIST_DOCUMENT_SUCCESS";
export const SET_TYPE_DOCUMENT = "SET_TYPE_DOCUMENT";
export const SET_ID_DOCUMENT = "SET_ID_DOCUMENT";
export const GET_DETAIL_DOCUMENT = "GET_DETAIL_DOCUMENT";
export const GET_DETAIL_DOCUMENT_SUCESS = "GET_DETAIL_DOCUMENT_SUCESS";
export const GET_DETAIL_DOCUMENT_ERROR = "GET_DETAIL_DOCUMENT_ERROR";
// trao đổi thông tin
export const GET_LIST_COMMENT = "GET_LIST_COMMENT";
export const GET_LIST_COMMENT_SUCESS = "GET_LIST_COMMENT_SUCESS";
export const GET_LIST_COMMENT_ERROR = "GET_LIST_COMMENT_ERROR";
export const GUI_Y_KIEN_TRAO_DOI = "GUI_Y_KIEN_TRAO_DOI";
export const GUI_Y_KIEN_TRAO_DOI_SUCESS = "GUI_Y_KIEN_TRAO_DOI_SUCESS";
export const GUI_Y_KIEN_TRAO_DOI_ERROR = "GUI_Y_KIEN_TRAO_DOI_ERROR";

// log comment document
export const GET_LOG_COMMENT_DOCUMENT = "GET_LOG_COMMENT_DOCUMENT";
export const GET_LOG_COMMENT_DOCUMENT_SUCESS = "GET_LOG_COMMENT_DOCUMENT_SUCESS";
export const GET_LOG_COMMENT_DOCUMENT_ERROR = "GET_LOG_COMMENT_DOCUMENT_ERROR";

// file đính kèm
export const GET_ATTACK_FILE_DOCUMENT = "GET_ATTACK_FILE_DOCUMENT";
export const GET_ATTACK_FILE_DOCUMENT_SUCESS = "GET_ATTACK_FILE_DOCUMENT_SUCESS";
export const GET_ATTACK_FILE_DOCUMENT_ERROR = "GET_ATTACK_FILE_DOCUMENT_ERROR";

// check button finish document
export const GET_FINISH_DOCUMENT_TYPE = "GET_FINISH_DOCUMENT";
export const GET_FINISH_DOCUMENT_TYPE_SUCCESS = "GET_FINISH_DOCUMENT_TYPE_SUCCESS";
export const GET_FINISH_DOCUMENT_TYPE_ERROR = "GET_FINISH_DOCUMENT_TYPE_ERROR";

// check signed document
export const GET_VIEW_FILE = "GET_VIEW_FILE";
export const GET_VIEW_FILE_SUCESS = "GET_VIEW_FILE_SUCESS";
export const GET_VIEW_FILE_ERROR = "GET_VIEW_FILE_ERROR";

// check button finish document
export const CHECK_SIGNED_DOCUMENT = "CHECK_SIGNED_DOCUMENT";
export const CHECK_SIGNED_DOCUMENT_RESULT = "CHECK_SIGNED_DOCUMENT_RESULT";

// lịch sử xử lý
export const GET_ACTIVITY_LOG = "GET_ACTIVITY_LOG";
export const GET_ACTIVITY_LOG_SUCESS = "GET_ACTIVITY_LOG_SUCESS";
export const GET_ACTIVITY_LOG_ERROR = "GET_ACTIVITY_LOG_ERROR";
export const SET_STATUS_ACTIVITY_LOG = "SET_STATUS_ACTIVITY_LOG";
// check finish document
export const GET_FINISH_DOCUMENT = "GET_FINISH_DOCUMENT";
export const GET_FINISH_DOCUMENT_SUCCESS = "GET_FINISH_DOCUMENT_SUCCESS";
export const GET_FINISH_DOCUMENT_ERROR = "GET_FINISH_DOCUMENT_ERROR";

// get list notification action
export const GET_LIST_NOTIFICATION = "GET_LIST_NOTIFICATION";
export const GET_LIST_NOTIFICATION_SUCCESS = "GET_LIST_NOTIFICATION_SUCCESS";
export const GET_LIST_NOTIFICATION_ERROR = "GET_LIST_NOTIFICATION_ERROR";
// luồng văn bản
export const GET_LUONG_VAN_BAN = "GET_LUONG_VAN_BAN";
export const GET_LUONG_VAN_BAN_SUCESS = "GET_LUONG_VAN_BAN_SUCESS";
export const GET_LUONG_VAN_BAN_ERORR = "GET_LUONG_VAN_BAN_ERORR";

// chuyển xử lý
export const GET_LIST_UNIT = "GET_LIST_UNIT";
export const GET_LIST_UNIT_SUCESS = "GET_LIST_UNIT_SUCESS";
export const GET_LIST_UNIT_ERROR = "GET_LIST_UNIT_ERROR";

