/**
 * Created by saionara1 on 6/21/17.
 */
import LocalizedStrings from "react-localization";

module.exports = new LocalizedStrings({
  en: {
    github_email: "Github Email",
    password: "Mật khẩu",
    empty_error: "Cannot be empty",
    sign_in: 'Sign In',
    list_title: 'Repositories',
    details: 'Details',
    tab_1: 'Tab1',
    tab_2: 'Tab2',
    tab_3: 'Tab3',
    logout: 'LogOut',
    logout_message: 'Are you sure you want to logout?',
    ok: 'Ok',
    cancel:'Cancel',
    account: 'Tên đăng nhập',
    chuyenTiep: 'Chuyển tiếp',
    traLoi: 'Trả lời',
    traLoiTatCa: 'Trả lời tất cả',
    guiToi: 'Gửi tới:',
    trL:'TrL:',
    tieuDe:'Tiêu đề:',
    noiDung:'Nội dung:',
    tapDinhKem:'Tập tin đính kèm',
    chonTep:'Chọn Tệp',
    luuNhap:'Lưu nháp',
    chonNguoiNhan: 'Chọn người nhận',
    chucNangDangPhatTrien: 'Chức năng đang được phát triển!',

    quanLyVanBan: 'Quản lý văn bản',
    vanBanDen: 'Văn bản đến',
    tongVanBanDangXuLy: 'Tổng số văn bản đang chờ xử lý',
    tongVanBanDen: 'Tổng số văn bản đến/quá hạn',
    tongVanBanDaXuLy: 'Tổng số văn bản đã xử lý',
    tongVanBanDaBanHanh: 'Tổng số văn bản đã ban hành',
    vanBanDi: 'Văn bản đi',
    quanLyCongViec: 'Quản lý công việc',
    congViecBanDangXuLy: 'Công việc đang chờ xử lý',
    congViecBanDen: 'Công việc đến/quá hạn',
    congViecBanDaXuLy: 'Công việc đã xử lý',
    congViecBanDaBanHanh: 'Công việc đã ban hành',
    tatCa: 'Tất cả',
    daDoc: 'Đã đọc',
    daXem: 'Đã xem',
    test: 'test 1',
    heThongVanBanDieuHanh: 'Hệ thống văn bản điều hành',

    // thông tin cá nhân
    gioiTinh: 'Giới tính:',
    ngaySinh: 'Ngày sinh:',
    dienThoai: 'Điện thoại:',
    email: 'Email:',
    tenDangNhap: 'Tên đăng nhập:',
    danToc: 'Dân tộc:',
    tonGiao: 'Tôn giáo:',
    hocVan: 'Tr.độ học vấn:',
    diaChi: 'Địa chỉ:',
    donVi: 'Đơn vị:',
    trangThai: 'Trạng thái:',
    matKhauCu: 'Mật khẩu cũ',
    matKhauMoi: 'Mật khẩu mới',
    xacNhanMatKhau: 'Xác nhận mật khẩu mới',
    capNhat: 'Cập nhật',
    // menu
    trangChu: 'Trang chủ',
    trangTinTuc: 'Trang tin tức',
    quanLyVanBan: 'Quản lý văn bản',
    vanBanChoXuLy: 'Văn bản chờ xử lý',
    vanBanDaXuLy: 'Văn bản đã xử lý',
    vanBanXemDeBiet: 'Văn bản Xem để biết',
    vanBanDanhDau: 'Văn bản đánh dấu',
    traCuuVanBan: 'Tra cứu văn bản',
    danhBa: 'Danh bạ',
    lichCongTacLanhDao: 'Lịch công tác lãnh đạo',
    thongTinDieuHanh: 'Thông tin điều hành',
    thongTinDieuHanhNhan: 'Thông tin điều hành nhận',
    thongTinDieuHanhGui: 'Thông tin điều hành gửi',
    baoCaoThongKe: 'Báo cáo thống kê',
    caiDatHeThong: 'Cài đặt hệ thống',
    thongTinCaNhan: 'Thông tin cá nhân',
    doiMatKhau: 'Đổi mật khẩu',
    thietLapMacDinh: 'Thiết lập mặc định',
    dangXuat: 'Đăng xuất',

    // cài đặt mặc định
    chonChucNangMacDinh: 'Chọn chức năng mặc định',
    thietLapMacDinh: 'Thiết lập mặc định',
    chucNangManHinh: 'Chức năng màn hình',
    chon: 'Chọn',

    // lịch họp
    noiDung: 'Nội dung:',
    thanhPhan: 'Thành phần:',
    diaDiem: 'Địa điểm:',
    sang: 'Sáng:',
    chieu: 'Chiều:',
    khongCoLichCongTac: 'Không có lịch công tác',

    // chi tiết văn bản
    chiTietVanBan: 'Chi tiết văn bản',
    chuyen: "Chuyển",
    ketThuc: "Kết thúc",
    danhDau: "Đánh dấu",
    huyDanhDau: "Hủy Đánh dấu",
    danhDauThanhCong: "Văn bản đã được đánh dấu!",
    huyDanhDauThanhCong: "Văn bản đã được bỏ đánh dấu!",
    ketThucVanBanThanhCong: "Kết thúc văn bản thành công!",
    trichYeu: 'Trích yếu:',
    soIOffice: 'Số ioffice:',
    CQBH: 'CQBH:',
    soKyHieu: 'Số ký hiệu:',
    ngayDen: 'Ngày đến:',
    ngayVB: 'Ngày VB:',
    hinhThucVB: 'Hình thức VB:',
    doKhan: 'Độ khẩn:',
    // view file
    noiDungFile: "Nội dung File",

    // modal dropdown
    choXuLy: "Chờ xử lý",
    dangXuLy: "Đang xử lý",
    daXuLy: "Đã xử lý",
    chuyenXuLy: "Chuyển xử lý",
    traoDoiThongTin: "Trao đổi thông tin",

    khongCoDuLieu: "Không có dữ liệu",
    thongBaoChuaChonNguoiNhanVanBan: "Chưa chọn đơn vị/cá nhân nhận văn bản",

    // chuyển văn bản
    xuLyChinh: "Xử lý chính",
    phoiHop: "Phối hợp",
    xemDeBiet: "Xem để biết",
    chonNguoiNhanVanBan: "Chọn người nhận văn bản",
    chonTheoNhomDonViNhan: "Chọn theo nhóm đơn vị nhận",
    chonTheoNhomCaNhanNhan: "Chọn theo nhóm cá nhân nhận",
    hoTen: "Họ tên",
    xlc: "XLC",
    ph: "PH",
    xem: "Xem",
    donVi: "Đơn vị",
    chonDonVi: "--Chọn đơn vị--",
  }
});
