# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'eOffice4' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    # Pods for eOffice4

    pod 'Firebase/Core'
    pod 'Firebase/Messaging'

  pod 'ReactNativeLocalization', :path => '../node_modules/react-native-localization'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

end
